baseURL: https://arraeofthings.com
title: Arraeofthings
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  logo: images/AR-ShortLogo.png
  subtitle:  Visual Artist
  copyright: All rights reserved. 
  author: Arraeofthings
  dontShowSource: false 
  portfolio:
    columns:
      desktop:
        default: 3
        archive: 5
      mobile:
        default: 2
        archive: 3
  socials:
    - icon: 'fab fa-twitter fa-lg'
      url: 'https://twitter.com/arraeofthings'
      landing: true
      new window: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/arraeofthings'
      landing: true
      new window: true
    - icon: 'fa fa-plus-circle'
      url: 'https://www.continuumspc.xyz'
      landing: true
      new window: true
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:contact@arraeofthings.com'
      landing: true
  homepage: "/work"
  specialPages:
    - work

  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/work"


menu:
   main:
     - name: Work
       url: /work/
       weight: 1
     - name: Statement
       url: /about/
       weight: 2
     - name: Studio
       url: https://www.continuumspc.xyz/
       weight: 3
